#!/bin/bash
awk -v w="$WATER" -v s="$STIR" 'BEGIN{a="ewwatratewa";b="ti.itirtrtr";c="bestchol";n=0;for(i=1;i<=length(w);i++)n=n*10+index(a,substr(w,i,1))-1;for(i=1;i<=length(s);i++)n=n*10+index(b,substr(s,i,1))-1;r="";while(n){r=substr(c,n%length(c)+1,1)r;n=int(n/length(c))}print(r?r:substr(c,1,1))}'
