#!/bin/bash
echo $(( $(echo $WATER | tr 'ewwatratewa' '0123456789') + $(echo $STIR | tr 'ti.itirtrtr' '0123456789') )) | awk '{b="bestchol";s="";v=$1;while(v){s=substr(b,(v%length(b))+1,1)s;v=int(v/length(b))}print (s?s:substr(b,1,1))}'
