#!/bin/bash
awk -v w="$WATER" -v s="$STIR" 'BEGIN{wa="ewwatratewa";st="ti.itirtrtr";b="bestchol";n1=0;n2=0;for(i=1;i<=length(w);i++)n1=n1*length(wa)+index(wa,substr(w,i,1))-1;for(i=1;i<=length(s);i++)n2=n2*length(st)+index(st,substr(s,i,1))-1;n=n1+n2;r="";while(n){r=substr(b,(n%length(b))+1,1)r;n=int(n/length(b))}if(r=="")r=substr(b,1,1);print r}'
